In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib
from matplotlib import font_manager, rc
sns.set(style='darkgrid')


rc('font', family='AppleGothic')
matplotlib.rcParams['axes.unicode_minus'] = False
%matplotlib inline

import warnings
warnings.filterwarnings("ignore")

In [2]:
lotte = pd.read_excel("../../../../Downloads/롯데마트자료.xlsx",usecols="A")
lotte

       지점명
0     서울역점
1      삼양점
2      중계점
3     청량리점
4      강변점
..     ...
125    수지점
126    양주점
127  천안아산점
128   의정부점
129    천안점

[130 rows x 1 columns]

In [3]:
a = ["롯데마트"+i.strip() for i in lotte.지점명]

In [4]:
from bs4 import BeautifulSoup
import urllib.request as req
import urllib.parse
import sys
import io

In [5]:
count = []
for i in a:
    try:
        plus_url = urllib.parse.quote_plus('"{}"'.format(i))
        url = "https://search.naver.com/search.naver?where=article&query={}&ie=utf8&st=rel&date_option=5&date_from=&date_to=&board=&srchby=text&dup_remove=1&cafe_url=&without_cafe_url=&sm=tab_opt&nso=so%3Ar%2Cp%3A1y%2Ca%3Aall&t=0&mson=0&prdtype=0".format(plus_url)

        res = req.urlopen(url).read()
        soup = BeautifulSoup(res, 'html.parser')
        title = soup.find(class_="title_num")
        
        count.append(title.text.split("/")[1].strip()[:-1])
        print(i,count[-1])
    except:
        count.append(0)
        print(i,count[-1])

롯데마트서울역점 479
롯데마트삼양점 65
롯데마트중계점 362
롯데마트청량리점 111
롯데마트강변점 35
롯데마트은평점 135
롯데마트송파점 143
롯데마트월드타워점 21
롯데마트잠실점 149
롯데마트구로점 107
롯데마트금천점 174
롯데마트김포공항점(롯데몰) 0
롯데마트양평점 130
롯데마트서초점 101
롯데마트광교점 115
롯데마트권선점 291
롯데마트수원점 26
롯데마트영통점 88
롯데마트천천점 79
롯데마트고양점 188
롯데마트주엽점 45
롯데마트화정점 123
롯데마트시화점 10
롯데마트시흥점 51
롯데마트시흥배곧점 35
롯데마트상록점 80
롯데마트선부점 47
롯데마트안산점 99
롯데마트신갈점 124
롯데마트수지점(롯데몰) 1
롯데마트덕소점 57
롯데마트마석점 19
롯데마트서현점 29
롯데마트판교점 53
롯데마트의정부점 24
롯데마트장암점 144
롯데마트이천점 7
롯데마트경기양평점 8
롯데마트구리점 117
롯데마트김포한강신도시점 7
롯데마트동두천점 51
롯데마트안성점 64
롯데마트오산점 132
롯데마트의왕점 235
롯데마트평택점 75
롯데마트부평점 339
롯데마트부평역점 64
롯데마트삼산점 190
롯데마트검단점 71
롯데마트청라점 84
롯데마트송도점 58
롯데마트연수점 49
롯데마트계양점 326
롯데마트영종도점 27
롯데마트인천터미널 6
롯데마트석사점 28
롯데마트원주점 16
롯데마트춘천점 87
롯데마트노은점 51
롯데마트대덕점 94
롯데마트서대전점 55
롯데마트상담점 41
롯데마트서청주점 86
롯데마트청주점 23
롯데마트제천점 10
롯데마트충주점 41
롯데마트성정점 182
롯데마트천안점 75
롯데마트당진점 148
롯데마트서산점 116
롯데마트아산터미널점 21
롯데마트홍성점 13
롯데마트광복점 58
롯데마트금정점 67
롯데마트동래점 54
롯데마트동부산점(롯데몰) 0
롯데마트부산점 61
롯데마트사상점(엄궁점) 0
롯데마트사하점 37
롯데마트화명점 343
롯데마트대구율하점 39
롯데마트칠성점 200
롯데마트울산점 159
롯데마트진장점 155
롯데마트구미점 30
롯데마트김천점 44
롯데마트마산점 203
롯데마트시티세븐점 10
롯데마트양덕점 189
롯데마트진해점 67
롯데마트창원중앙점 86
롯데마트김해점 44
롯데마트장유점 72
롯데마트거제점 135
롯데마트웅상점 30
롯데마트통영점 47
롯데마트진주점 20
롯데마트상무점 73
롯데마트수완점 101
롯데마트월드컵점 99
롯데마트첨단점 53
롯데마트군산점 97
롯데마트남원점 18
롯데마트송천점 79
롯데마트익산점 67
롯데마트전주점 54
롯데마트정읍점 8
롯데마트여수점 34
롯데마트여천점 26
롯데마트나주점 6
롯데마트목포점 68
롯데마트남악점 7
롯데마트제주점 38
롯데마트롯데식품관 평존점 0
롯데마트포항두호점 1
롯데마트동탄점 0
롯데마트고덕점 0
롯데마트해운대점 0
롯데마트서대구점 0
롯데마트관악점 0
롯데마트와스타디움점 0
롯데마트항동점 1
롯데마트반여점 3
롯데마트김포점 4
롯데마트동대전점 8
롯데마트수지점 86
롯데마트양주점 57
롯데마트천안아산점 57
롯데마트의정부점 24
롯데마트천안점 75

In [6]:
len(count)

130

In [7]:
lotte["카페(1년)"] = count

In [8]:
lotte.to_excel("../../../../Downloads/롯데마트자료(카페).xlsx",encoding="cp949",index=False)