In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib
from matplotlib import font_manager, rc
sns.set(style='darkgrid')


rc('font', family='AppleGothic')
matplotlib.rcParams['axes.unicode_minus'] = False
%matplotlib inline

import warnings
warnings.filterwarnings("ignore")

In [2]:
home = pd.read_excel("../../../../Downloads/홈플.xlsx")
home

       지점명
0      강동점
1      강서점
2     신도림점
3      금천점
4      중계점
..     ...
138  청주성안점
139  칠곡IC점
140    상주점
141  부천중동점
142   동김해점

[143 rows x 1 columns]

In [3]:
a = [ "홈플러스"+i for i in home.지점명]

In [4]:
a

['홈플러스강동점',
 '홈플러스강서점',
 '홈플러스신도림점',
 '홈플러스금천점',
 '홈플러스중계점',
 '홈플러스방학점',
 '홈플러스합정점',
 '홈플러스월드컵점',
 '홈플러스월곡점',
 '홈플러스잠실점',
 '홈플러스영등포점',
 '홈플러스면목점',
 '홈플러스상봉점',
 '홈플러스신내점',
 '홈플러스계산점',
 '홈플러스작전점',
 '홈플러스인하점',
 '홈플러스간석점',
 '홈플러스구월점',
 '홈플러스인천논현점',
 '홈플러스가좌점',
 '홈플러스인천청라점',
 '홈플러스송도점',
 '홈플러스고양터미널점',
 '홈플러스일산점',
 '홈플러스킨텍스점',
 '홈플러스김포점',
 '홈플러스김포풍무점',
 '홈플러스진접점',
 '홈플러스부천소사점',
 '홈플러스부천여월점',
 '홈플러스부천상동점',
 '홈플러스야탑점',
 '홈플러스서수원점',
 '홈플러스영통점',
 '홈플러스원천점',
 '홈플러스북수원점',
 '홈플러스동수원점',
 '홈플러스선부점',
 '홈플러스안산점',
 '홈플러스평촌점',
 '홈플러스안양점',
 '홈플러스오산점',
 '홈플러스의정부점',
 '홈플러스파주문산점',
 '홈플러스파주운정점',
 '홈플러스송탄점',
 '홈플러스평택안중점',
 '홈플러스포천송우점',
 '홈플러스하남점',
 '홈플러스병점점',
 '홈플러스화성향남점',
 '홈플러스강릉점',
 '홈플러스삼척점',
 '홈플러스원주점',
 '홈플러스춘천점',
 '홈플러스동청주점',
 '홈플러스오창점',
 '홈플러스청주점',
 '홈플러스세종점',
 '홈플러스조치원점',
 '홈플러스대전가오점',
 '홈플러스대전둔산점',
 '홈플러스대전탄방점',
 '홈플러스서대전점',
 '홈플러스유성점',
 '홈플러스문화점',
 '홈플러스계룡점',
 '홈플러스논산점',
 '홈플러스보령점',
 '홈플러스천안점',
 '홈플러스김제점',
 '홈플러스익산점',
 '홈플러스전주점',
 '홈플러스전주효자점',
 '홈플러스계림점',
 '홈플러스동광주점',
 '홈플러스광양점',
 '홈플러스목포점',
 '홈플러스순천점',
 '홈플러스남대구점',
 '홈플러스성서점',
 '홈플러스동촌점',
 '홈플러스칠곡점',
 '홈플러스내당점',
 '홈플러스대구스타디움점',
 '홈플러스대구수성점',
 '홈플러스경산점',
 '홈플러스경주점',
 '홈플러스구미점',
 '홈플러스문경점',
 '홈플러스안동점',
 '홈플러스영주점',
 '홈플러스포항점',
 '홈플러스죽도점',
 '홈플러스부산감만점',
 '홈플러스동래점',
 '홈플러스가야점',
 '홈플러스서면점',
 '홈플러스장림점',
 '홈플러스아시아드점',
 '홈플러스부산연산점',
 '홈플러스영도점',
 '홈플러스부산반여점',
 '홈플러스센텀시티점',
 '홈플러스부산정관점',
 '홈플러스울산남구점',
 '홈플러스울산동구점',
 '홈플러스울산북구점',
 '홈플러스울산점',
 '홈플러스거제점',
 '홈플러스김해점',
 '홈플러스밀양점',
 '홈플러스삼천포점',
 '홈플러스진주점',
 '홈플러스마산점',
 '홈플러스창원점',
 '홈플러스진해점',
 '홈플러스서귀포점',
 '홈플러스가양점',
 '홈플러스동대문점',
 '홈플러스목동점',
 '홈플러스서울남현점',
 '홈플러스시흥점',
 '홈플러스분당오리점',
 '홈플러스시화점',
 '홈플러스안산고잔점',
 '홈플러스화성동탄점',
 '홈플러스인천연수점',
 '홈플러스광주하남점',
 '홈플러스대구점',
 '홈플러스상인점',
 '홈플러스동대전점',
 '홈플러스서부산점',
 '홈플러스해운대점',
 '홈플러스순천풍덕점',
 '홈플러스전주완산점',
 '홈플러스천안신방점',
 '홈플러스청주성안점',
 '홈플러스칠곡IC점',
 '홈플러스상주점',
 '홈플러스부천중동점',
 '홈플러스동김해점']

In [5]:
import requests 
from bs4 import BeautifulSoup 
from selenium import webdriver as wd 
from selenium.webdriver.common.by import By 
from selenium.webdriver.support.ui import WebDriverWait 
from selenium.webdriver.support import expected_conditions as EC 
import time 
import re

In [6]:
from selenium.webdriver.chrome.options import Options

chrome_options = Options()

chrome_options.add_argument("--headless")

In [14]:
count = []

for i in a:
    try:
        url = "https://www.instagram.com/explore/tags/{}/".format(i)

        driver = wd.Chrome(chrome_options=chrome_options,executable_path="../../../../study/html/chromedriver")
        driver.get(url)
        time.sleep(5)
        data = driver.find_element_by_class_name('g47SY').text
        count.append(data)
        print(i)
    except:
        print("실패: ",i)
        count.append("fail")

홈플러스강동점
홈플러스강서점
홈플러스신도림점
홈플러스금천점
홈플러스중계점
홈플러스방학점
홈플러스합정점
홈플러스월드컵점
홈플러스월곡점
홈플러스잠실점
홈플러스영등포점
홈플러스면목점
홈플러스상봉점
홈플러스신내점
홈플러스계산점
홈플러스작전점
홈플러스인하점
홈플러스간석점
홈플러스구월점
홈플러스인천논현점
홈플러스가좌점
홈플러스인천청라점
홈플러스송도점
홈플러스고양터미널점
홈플러스일산점
홈플러스킨텍스점
홈플러스김포점
홈플러스김포풍무점
홈플러스진접점
홈플러스부천소사점
홈플러스부천여월점
홈플러스부천상동점
홈플러스야탑점
홈플러스서수원점
홈플러스영통점
홈플러스원천점
홈플러스북수원점
홈플러스동수원점
홈플러스선부점
홈플러스안산점
홈플러스평촌점
홈플러스안양점
홈플러스오산점
홈플러스의정부점
홈플러스파주문산점
홈플러스파주운정점
홈플러스송탄점
홈플러스평택안중점
홈플러스포천송우점
홈플러스하남점
홈플러스병점점
홈플러스화성향남점
홈플러스강릉점
홈플러스삼척점
홈플러스원주점
홈플러스춘천점
홈플러스동청주점
홈플러스오창점
홈플러스청주점
홈플러스세종점
홈플러스조치원점
홈플러스대전가오점
홈플러스대전둔산점
홈플러스대전탄방점
홈플러스서대전점
홈플러스유성점
홈플러스문화점
홈플러스계룡점
홈플러스논산점
홈플러스보령점
홈플러스천안점
홈플러스김제점
홈플러스익산점
홈플러스전주점
홈플러스전주효자점
홈플러스계림점
홈플러스동광주점
홈플러스광양점
홈플러스목포점
홈플러스순천점
홈플러스남대구점
홈플러스성서점
홈플러스동촌점
홈플러스칠곡점
홈플러스내당점
홈플러스대구스타디움점
홈플러스대구수성점
홈플러스경산점
홈플러스경주점
홈플러스구미점
홈플러스문경점
홈플러스안동점
홈플러스영주점
홈플러스포항점
홈플러스죽도점
홈플러스부산감만점
홈플러스동래점
홈플러스가야점
홈플러스서면점
홈플러스장림점
홈플러스아시아드점
홈플러스부산연산점
실패:  홈플러스영도점
실패:  홈플러스부산반여점
홈플러스센텀시티점
홈플러스부산정관점
홈플러스울산남구점
홈플러스울산동구점
홈플러스울산북구점
홈플러스울산점
홈플러스거제점
홈플러스김해점
홈플러스밀양점
홈플러스삼천포점
홈플러스진주점
홈플러스마산점
홈플러스창원점
홈플러스진해점
홈플러스서귀포점
홈플러스가양점
홈플러스동대문점
홈플러스목동점
홈플러스서울남현점
홈플러스시흥점
홈플러스분당오리점
홈플러스시화점
홈플러스안산고잔점
홈플러스화성동탄점
홈플러스인천연수점
홈플러스광주하남점
홈플러스대구점
홈플러스상인점
홈플러스동대전점
홈플러스서부산점
홈플러스해운대점
홈플러스순천풍덕점
홈플러스전주완산점
홈플러스천안신방점
홈플러스청주성안점
실패:  홈플러스칠곡IC점
실패:  홈플러스상주점
홈플러스부천중동점
실패:  홈플러스동김해점

In [16]:
len(count)

143

In [13]:
try:    
    url = "https://www.instagram.com/explore/tags/홈플러스영도점/"
    driver = wd.Chrome(chrome_options=chrome_options,executable_path="../../../../study/html/chromedriver")
    driver.get(url)
    # driver
    time.sleep(10)
    data = driver.find_element_by_class_name('g47SY').text
    data
except:
        print("err")

err

In [17]:
home["게시물수"] = count

In [19]:
home

       지점명   게시물수
0      강동점    434
1      강서점  1,323
2     신도림점     51
3      금천점    547
4      중계점    424
..     ...    ...
138  청주성안점     28
139  칠곡IC점   fail
140    상주점   fail
141  부천중동점      0
142   동김해점   fail

[143 rows x 2 columns]

In [20]:
home.iloc[141,1] = 48

In [22]:
home[home["게시물수"]=="fail"]

       지점명  게시물수
102    영도점  fail
103  부산반여점  fail
139  칠곡IC점  fail
140    상주점  fail
142   동김해점  fail

In [23]:
home.to_excel("../../../../Downloads/홈플.xlsx",encoding="cp949",index=False)