In [1]:
import numpy as np
import pandas as pd

In [2]:
population = pd.read_excel("../데이터/인구수/구별 인구수.xlsx",header=1)

In [3]:
population.fillna(method="pad", inplace = True)

In [4]:
population.rename(columns= {"행정구역(동읍면)별":"광역시도",
                           "항목":'시자치구',
                           '계':'인구수'},inplace=True)

# population = population[(population['시자치구'] != '소계')]

In [5]:
population.is_copy = False

population.rename(columns= {"항목.1":"구분"},inplace=True)


population.loc[population["구분"]=="총인구수 (명)","구분"] = "합계"
population.loc[population["구분"]=="남자인구수 (명)","구분"] = "남자"
population.loc[population["구분"]=="여자인구수 (명)","구분"] = "여자"

In [6]:
population

,광역시도,시자치구,구분,인구수,0 - 4세,5 - 9세,10 - 14세,15 - 19세,20 - 24세,25 - 29세,...,55 - 59세,60 - 64세,65 - 69세,70 - 74세,75 - 79세,80 - 84세,85 - 89세,90 - 94세,95 - 99세,100+
0,전국,소계,합계,51841371,1770084,2319378,2307180,2564901,3296969,3507381,...,4288202,3808870,2672447,2011644,1634477,1125390,558417,194910,47503,21060
1,전국,소계,남자,25856030,907897,1189600,1189572,1332502,1722121,1853037,...,2159030,1881454,1286749,939180,697579,420651,166774,44476,10306,5104
2,전국,소계,여자,25985341,862187,1129778,1117608,1232399,1574848,1654344,...,2129172,1927416,1385698,1072464,936898,704739,391643,150434,37197,15956
3,서울특별시,소계,합계,9724496,288210,360699,370115,433077,643050,820870,...,755939,700896,511059,395107,299851,183704,85125,32118,9075,6511
4,서울특별시,소계,남자,4735431,148196,185052,190428,221434,308861,404175,...,368757,333031,239470,181341,135576,75268,28311,8355,2421,1700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,제주특별자치도,제주시,남자,245567,10431,13541,13594,14493,16895,16164,...,19332,15761,10215,7614,5665,3481,1501,307,63,25
797,제주특별자치도,제주시,여자,244167,9652,13037,12462,13059,14945,14627,...,18534,15722,10818,8747,7486,6142,4051,1647,644,145
798,제주특별자치도,서귀포시,합계,181059,6239,8639,8701,8712,9853,9221,...,15546,13952,9812,8308,7009,5065,2963,866,332,101
799,제주특별자치도,서귀포시,남자,91544,3191,4439,4529,4571,5313,4914,...,8156,7067,4758,3936,3017,1863,801,139,37,10
800,제주특별자치도,서귀포시,여자,89515,3048,4200,4172,4141,4540,4307,...,7390,6885,5054,4372,3992,3202,2162,727,295,91