In [ ]:
# !pip install googlemaps

In [1]:
import googlemaps

In [2]:
gmaps_key = "AIzaSyDtcNjA4Ky-opsUF4_W4Qevy9VYqeoemdE" # 이거 제 api 키인데 직접 받으셔도 되구 쓰셔도 되용
gmaps = googlemaps.Client(key = gmaps_key)

In [3]:
import pandas as pd

In [4]:
emart = pd.read_excel("../TeamProjectData/이마트 데이터.xlsx")
emart.지역.fillna(method='pad',inplace=True)

FileNotFoundError: [Errno 2] No such file or directory: '../TeamProjectData/이마트 데이터.xlsx'

In [ ]:
emart

In [ ]:
emart_branch = emart.지점명

In [ ]:
emart_branch

In [5]:
gmaps.geocode("이마트 청계천점",language="ko")

[{'address_components': [{'long_name': '７７３−９',
    'short_name': '７７３−９',
    'types': ['premise']},
   {'long_name': '원시동',
    'short_name': '원시동',
    'types': ['political', 'sublocality', 'sublocality_level_2']},
   {'long_name': '단원구',
    'short_name': '단원구',
    'types': ['political', 'sublocality', 'sublocality_level_1']},
   {'long_name': '안산시',
    'short_name': '안산시',
    'types': ['locality', 'political']},
   {'long_name': '경기도',
    'short_name': '경기도',
    'types': ['administrative_area_level_1', 'political']},
   {'long_name': '대한민국',
    'short_name': 'KR',
    'types': ['country', 'political']},
   {'long_name': '425-090',
    'short_name': '425-090',
    'types': ['postal_code']}],
  'formatted_address': '대한민국 경기도 안산시 단원구 원시동 773-9',
  'geometry': {'location': {'lat': 37.3143754, 'lng': 126.7972518},
   'location_type': 'ROOFTOP',
   'viewport': {'northeast': {'lat': 37.31572438029149,
     'lng': 126.7986007802915},
    'southwest': {'lat': 37.3130264197085, 'lng': 126.7959028197085}}},
  'partial_match': True,
  'place_id': 'ChIJSWSfxTtuezURDjoLaQ9chH0',
  'plus_code': {'compound_code': '8Q7W+QW 대한민국 경기도 안산시',
   'global_code': '8Q988Q7W+QW'},
  'types': ['street_address']},
 {'address_components': [{'long_name': '６３',
    'short_name': '６３',
    'types': ['premise']},
   {'long_name': '동산로',
    'short_name': '동산로',
    'types': ['political', 'sublocality', 'sublocality_level_4']},
   {'long_name': '초지동',
    'short_name': '초지동',
    'types': ['political', 'sublocality', 'sublocality_level_2']},
   {'long_name': '단원구',
    'short_name': '단원구',
    'types': ['political', 'sublocality', 'sublocality_level_1']},
   {'long_name': '안산시',
    'short_name': '안산시',
    'types': ['locality', 'political']},
   {'long_name': '경기도',
    'short_name': '경기도',
    'types': ['administrative_area_level_1', 'political']},
   {'long_name': '대한민국',
    'short_name': 'KR',
    'types': ['country', 'political']},
   {'long_name': '425-090',
    'short_name': '425-090',
    'types': ['postal_code']}],
  'formatted_address': '대한민국 경기도 안산시 단원구 초지동 동산로 63',
  'geometry': {'location': {'lat': 37.3143754, 'lng': 126.7972518},
   'location_type': 'ROOFTOP',
   'viewport': {'northeast': {'lat': 37.31572438029149,
     'lng': 126.7986007802915},
    'southwest': {'lat': 37.3130264197085, 'lng': 126.7959028197085}}},
  'partial_match': True,
  'place_id': 'ChIJSWSfxTtuezURTNwtAlh5tQs',
  'plus_code': {'compound_code': '8Q7W+QW 대한민국 경기도 안산시',
   'global_code': '8Q988Q7W+QW'},
  'types': ['street_address']}]

In [25]:
emart_branch_name = ["이마트 "+ name  for name in emart_branch]
emart_branch_name

['이마트 청계천점',
 '이마트 용산점',
 '이마트 창동점',
 '이마트 미아점',
 '이마트 하월곡점',
 '이마트 월계점',
 '이마트 이문점',
 '이마트 묵동점',
 '이마트 상봉점',
 '이마트 성수점',
 '이마트 왕십리점',
 '이마트 자양점',
 '이마트 명일점',
 '이마트 천호점',
 '이마트 가든파이브점',
 '이마트 양재점',
 '이마트 역삼점',
 '이마트 수서점',
 '이마트 이수점',
 '이마트 가양점',
 '이마트 목동점',
 '이마트 신월점',
 '이마트 여의도점',
 '이마트 영등포점',
 '이마트 구로점',
 '이마트 신도림점',
 '이마트 수색점',
 '이마트 은평점',
 '이마트 마포점',
 '이마트 동백점',
 '이마트 보라점',
 '이마트 수지점',
 '이마트 용인점',
 '이마트 죽전점',
 '이마트 흥덕점',
 '이마트 일산점',
 '이마트 킨텍스점',
 '이마트 풍산점',
 '이마트 화정점',
 '이마트 남양주점',
 '이마트 다산점',
 '이마트 별내점',
 '이마트 진접점',
 '이마트 광교점',
 '이마트 서수원점',
 '이마트 수원점',
 '이마트 광명점',
 '이마트 광명소하점',
 '이마트 부천점',
 '이마트 중동점',
 '이마트 분당점',
 '이마트 성남점',
 '이마트 안양점',
 '이마트 평촌점',
 '이마트 파주점',
 '이마트 파주운정점',
 '이마트 동탄점',
 '이마트 화성봉담점',
 '이마트 경기광주점',
 '이마트 고잔점',
 '이마트 과천점',
 '이마트 김포한강점',
 '이마트 산본점',
 '이마트 시화점',
 '이마트 안성점',
 '이마트 양주점',
 '이마트 여주점',
 '이마트 오산점',
 '이마트 의왕점',
 '이마트 의정부점',
 '이마트 이천점',
 '이마트 평택점',
 '이마트 포천점',
 '이마트 하남점',
 '이마트 검단점',
 '이마트 계양점',
 '이마트 동인천점',
 '이마트 연수점',
 '이마트 인천공항점',
 '이마트 강릉점',
 '이마트 동해점',
 '이마트 속초점',
 '이마트 원주점',
 '이마트 춘천점',
 '이마트 태백점',
 '이마트 대전터미널점',
 '이마트 둔산점',
 '이마트 세종점',
 '이마트 제천점',
 '이마트 청주점',
 '이마트 충주점',
 '이마트 천안점',
 '이마트 천안서북점',
 '이마트 천안터미널점',
 '이마트 펜타포트점',
 '이마트 보령점',
 '이마트 서산점',
 '이마트 아산점',
 '이마트 금정점',
 '이마트 문현점',
 '이마트 사상점',
 '이마트 연제점',
 '이마트 해운대점',
 '이마트 감삼점',
 '이마트 성서점',
 '이마트 월배점',
 '이마트 반야월점',
 '이마트 칠성점',
 '이마트 만촌점',
 '이마트 울산점',
 '이마트 경산점',
 '이마트 구미점',
 '이마트 동구미점',
 '이마트 김천점',
 '이마트 상주점',
 '이마트 안동점',
 '이마트 영천점',
 '이마트 포항점',
 '이마트 포항이동점',
 '이마트 김해점',
 '이마트 마산점',
 '이마트 사천점',
 '이마트 양산점',
 '이마트 진주점',
 '이마트 창원점',
 '이마트 통영점',
 '이마트 광산점',
 '이마트 광주점',
 '이마트 동광주점',
 '이마트 봉선점',
 '이마트 군산점',
 '이마트 남원점',
 '이마트 익산점',
 '이마트 전주점',
 '이마트 전주에코시티점',
 '이마트 목포점',
 '이마트 순천점',
 '이마트 여수점',
 '이마트 서귀포점',
 '이마트 신제주점',
 '이마트 제주점']

In [26]:
emart_address = []
emart_lat = []
emart_lng = []

for name in emart_branch_name:
    tmp = gmaps.geocode(name, language = "ko")
    emart_address.append(tmp[0].get("formatted_address"))
    
    tmp_loc = tmp[0].get("geometry")
    
    emart_lat.append(tmp_loc["location"]["lat"])
    
    emart_lng.append(tmp_loc["location"]["lng"])
    
    print(name + "--->" + tmp[0].get("formatted_address"))

이마트 청계천점--->대한민국 서울특별시 중구 황학동 청계천로 400
이마트 용산점--->대한민국 서울특별시 용산구 한강로3가 한강대로23길 55
이마트 창동점--->대한민국 서울특별시 도봉구 창동 노해로65길 4
이마트 미아점--->대한민국 서울특별시 성북구 길음동 도봉로 17
이마트 하월곡점--->대한민국 서울특별시 성북구 하월곡동 230
이마트 월계점--->대한민국 서울특별시 노원구 월계3동 마들로3길 15
이마트 이문점--->대한민국 서울특별시 동대문구 이문1동 이문로 136
이마트 묵동점--->대한민국 서울특별시 중랑구 묵동 동일로 932
이마트 상봉점--->대한민국 서울특별시 중랑구 망우동 상봉로 118
이마트 성수점--->대한민국 서울특별시 성동구 성수2가1동 성수2가1동 뚝섬로 379
이마트 왕십리점--->대한민국 서울특별시 성동구 행당1동 왕십리광장로 17
이마트 자양점--->대한민국 서울특별시 광진구 자양3동 아차산로 272
이마트 명일점--->대한민국 서울특별시 강동구 명일2동 고덕로 276
이마트 천호점--->대한민국 서울특별시 강동구 천호동 천호대로 1017
이마트 가든파이브점--->대한민국 서울특별시 송파구 문정2동 충민로 10
이마트 양재점--->대한민국 서울특별시 서초구 양재2동 매헌로
이마트 역삼점--->대한민국 서울특별시 강남구 역삼2동 역삼로 310
이마트 수서점--->대한민국 서울특별시 강남구 수서동 광평로 280
이마트 이수점--->대한민국 서울특별시 동작구 사당동 사당로 300
이마트 가양점--->대한민국 서울특별시 강서구 가양동 449-19
이마트 목동점--->대한민국 서울특별시 양천구 목1동 962
이마트 신월점--->대한민국 서울특별시 양천구 신월동 화곡로 59
이마트 여의도점--->대한민국 서울특별시 영등포구 여의도동 여의동로3길 10
이마트 영등포점--->대한민국 SEOUL YEONGDEUNGPO-GU 영등포동
이마트 구로점--->대한민국 서울특별시 구로구 구로동 디지털로32길 43
이마트 신도림점--->대한민국 서울특별시 구로구 구로동 새말로 97
이마트 수색점--->대한민국 서울특별시 은평구 수색동 수색로 217
이마트 은평점--->대한민국 서울특별시 은평구 응암1동 은평로 111
이마트 마포점--->대한민국 서울특별시 마포구 공덕동 백범로 212
이마트 동백점--->대한민국 경기도 용인시 기흥구 중동 동백죽전대로 444
이마트 보라점--->대한민국 경기도 용인시 기흥구 상갈동 한보라1로 92
이마트 수지점--->대한민국 경기도 용인시 수지구 신봉동 수지로 203
이마트 용인점--->대한민국 경기도 용인시 처인구 역삼동 명지로 53
이마트 죽전점--->대한민국 경기도 용인시 수지구 죽전2동 포은대로 552
이마트 흥덕점--->대한민국 경기도 용인시 기흥구 영덕동 흥덕중앙로 60
이마트 일산점--->대한민국 경기도 고양시 일산동구 중앙로 1124
이마트 킨텍스점--->대한민국 경기도 고양시 일산서구 송포동 킨텍스로 171
이마트 풍산점--->대한민국 경기도 고양시 일산동구 풍산동 무궁화로 237
이마트 화정점--->대한민국 경기도 고양시 덕양구 화정2동 백양로 79
이마트 남양주점--->대한민국 경기도 남양주시 호평동 늘을2로 27
이마트 다산점--->대한민국 경기도 남양주시 도농동 도농로 24
이마트 별내점--->대한민국 경기도 남양주시 별내동 순화궁로 167
이마트 진접점--->대한민국 경기도 남양주시 진접읍 금강로유연들1길 154
이마트 광교점--->대한민국 경기도 수원시 영통구 원천동 광교로 191
이마트 서수원점--->대한민국 경기도 수원시 권선구 구운동 수인로 291
이마트 수원점--->대한민국 경기도 수원시 권선구 권선2동 경수대로 270
이마트 광명점--->대한민국 경기도 광명시 광명동 150-19
이마트 광명소하점--->대한민국 경기도 광명시 소하동 소하로 97
이마트 부천점--->대한민국 경기도 부천시 심곡본동 부천로 1
이마트 중동점--->대한민국 경기도 부천시 원미구 중1동 석천로 188
이마트 분당점--->대한민국 경기도 성남시 분당구 정자동 불정로 134
이마트 성남점--->대한민국 경기도 성남시 수정구 태평동 수정로 201
이마트 안양점--->대한민국 경기도 안양시 동안구 비산동 411-8
이마트 평촌점--->대한민국 경기도 안양시 동안구 관양동 시민대로 300
이마트 파주점--->대한민국 경기도 파주시 교하동 당하길 10
이마트 파주운정점--->대한민국 경기도 파주시 운정3동 한울로 123
이마트 동탄점--->대한민국 경기도 화성시 동탄1동 동탄중앙로 376
이마트 화성봉담점--->대한민국 경기도 화성시 봉담읍 효행로 278
이마트 경기광주점--->대한민국 경기도 광주시 경안동 광주대로 30
이마트 고잔점--->대한민국 경기도 안산시 단원구 초지동 원포공원1로 46
이마트 과천점--->대한민국 경기도 과천시 별양동 별양상가3로 11 KR
이마트 김포한강점--->대한민국 경기도 김포시 구래동 6880-9
이마트 산본점--->대한민국 경기도 군포시 광정동 산본로 347
이마트 시화점--->대한민국 경기도 시흥시 정왕본동 1734-1
이마트 안성점--->대한민국 경기도 안성시 안성2동 중앙로 246
이마트 양주점--->대한민국 경기도 양주시 회정동 평화로 1713
이마트 여주점--->대한민국 경기도 여주군 여주읍 홍문리 384-1
이마트 오산점--->대한민국 경기도 오산시 대원동 경기대로 181
이마트 의왕점--->대한민국 경기도 의왕시 오전동 789
이마트 의정부점--->대한민국 경기도 의정부시 송산2동 민락로 210
이마트 이천점--->대한민국 경기도 이천시 증포동 47-4
이마트 평택점--->대한민국 경기도 평택시 세교동 영신로 29
이마트 포천점--->대한민국 경기도 포천시 설운동 호국로 915
이마트 하남점--->대한민국 경기도 하남시 덕풍3동 덕풍서로 70
이마트 검단점--->대한민국 인천광역시 서구 당하동 서곶로 754
이마트 계양점--->대한민국 인천광역시 계양구 작전서운동 봉오대로 785
이마트 동인천점--->대한민국 인천광역시 중구 신생동 인중로 134
이마트 연수점--->대한민국 인천광역시 연수구 동춘동 926-9
이마트 인천공항점--->대한민국 인천광역시 중구 운서동 공항로424번길 36
이마트 강릉점--->대한민국 강원도 강릉시 송정동 경강로 2398-10
이마트 동해점--->대한민국 강원도 동해시 천곡동 천곡로 100
이마트 속초점--->대한민국 강원도 속초시 청호동 청호대교로 12
이마트 원주점--->대한민국 강원도 원주시 무실동 북원로 1928
이마트 춘천점--->대한민국 강원도 춘천시 온의동 경춘로 2341
이마트 태백점--->대한민국 강원도 태백시 화전동 113
이마트 대전터미널점--->대한민국 대전광역시 동구 용전동 동서대로 1689
이마트 둔산점--->대한민국 대전광역시 서구 둔산동 둔산북로 41
이마트 세종점--->대한민국 세종특별자치시 남면 금송로 687
이마트 제천점--->대한민국 충청북도 제천시 강제동 장평천로 11
이마트 청주점--->대한민국 충청북도 청주시 흥덕구 산남동 청남로 1853
이마트 충주점--->대한민국 충청북도 충주시 문화동 1024
이마트 천안점--->대한민국 충청남도 천안시 서북구 충무로 187
이마트 천안서북점--->대한민국 충청남도 천안시 서북구 부성동 삼성대로 20
이마트 천안터미널점--->대한민국 충청남도 천안시 동남구 신부동 만남로 43
이마트 펜타포트점--->대한민국 충청남도 천안시 서북구 백석동 공원로 196
이마트 보령점--->대한민국 충청남도 보령시 궁촌동 340-1
이마트 서산점--->대한민국 충청남도 서산시 동문1동 서해로 3685
이마트 아산점--->대한민국 충청남도 아산시 풍기동 온천대로 1678
이마트 금정점--->대한민국 부산광역시 금정구 구서동 중앙대로1841번길 24
이마트 문현점--->대한민국 부산광역시 남구 문현동 전포대로91번길 47
이마트 사상점--->대한민국 부산광역시 사상구 괘법동 광장로 17
이마트 연제점--->대한민국 부산광역시 연제구 연산동 연수로 89
이마트 해운대점--->대한민국 부산광역시 해운대구 중동 좌동순환로 511
이마트 감삼점--->대한민국 대구광역시 달서구 감삼동 521
이마트 성서점--->대한민국 대구광역시 달서구 이곡동 이곡동로 24
이마트 월배점--->대한민국 대구광역시 달서구 대천동 555
이마트 반야월점--->대한민국 대구광역시 동구 신서동 520-1
이마트 칠성점--->대한민국 대구광역시 북구 칠성동 침산로 93
이마트 만촌점--->대한민국 대구광역시 수성구 만촌1동 동원로 136
이마트 울산점--->대한민국 울산광역시 남구 삼산동 남중로 48
이마트 경산점--->대한민국 경상북도 경산시 중산동 옥산로 227
이마트 구미점--->대한민국 경상북도 구미시 광평동 65-1
이마트 동구미점--->대한민국 경상북도 구미시 임수동 이계북로 23
이마트 김천점--->대한민국 경상북도 김천시 신음동 시청로 75
이마트 상주점--->대한민국 경상북도 상주시 만산동 경상대로 3141
이마트 안동점--->대한민국 경상북도 안동시 옥동 796-1
이마트 영천점--->대한민국 경상북도 영천시 오수동 286
이마트 포항점--->대한민국 경상북도 포항시 남구 인덕동 냉천로 10
이마트 포항이동점--->대한민국 경상북도 포항시 북구 득량동 대이로 188
이마트 김해점--->대한민국 경상남도 김해시 외동 김해대로 2232
이마트 마산점--->대한민국 경상남도 창원시 마산합포구 동서동 서성로 3
이마트 사천점--->대한민국 경상남도 사천시 선구동 삼천포대교로 591
이마트 양산점--->대한민국 경상남도 양산시 중부동 양산역6길 12
이마트 진주점--->대한민국 경상남도 진주시 인사동 진양호로 477
이마트 창원점--->대한민국 경상남도 창원시 성산구 중앙동 원이대로 608
이마트 통영점--->대한민국 경상남도 통영시 광도면 죽림4로 9
이마트 광산점--->대한민국 광주광역시 광산구 우산동 사암로 172
이마트 광주점--->대한민국 광주광역시 서구 화정1동 죽봉대로 61
이마트 동광주점--->대한민국 광주광역시 동구 계림동 중앙로 358
이마트 봉선점--->대한민국 광주광역시 남구 봉선동 봉선로 198
이마트 군산점--->대한민국 전라북도 군산시 경암동 구암3.1로 137
이마트 남원점--->대한민국 전라북도 남원시 남문로 385-16
이마트 익산점--->대한민국 전라북도 익산시 동산동 667-53
이마트 전주점--->대한민국 전라북도 전주시 완산구 서신동 당산로 111
이마트 전주에코시티점--->대한민국 전라북도 전주시 완산구 서신동 당산로 111
이마트 목포점--->대한민국 전라남도 목포시 옥암동 915-25
이마트 순천점--->대한민국 전라남도 순천시 덕암동 팔마로 191
이마트 여수점--->대한민국 전라남도 여수시 광림동 좌수영로 277
이마트 서귀포점--->대한민국 제주특별자치도 서귀포시 법환동 일주동로 9209
이마트 신제주점--->대한민국 제주특별자치도 제주시 노형동 1100로 3348
이마트 제주점--->대한민국 제주특별자치도 제주시 삼도2동 탑동로 38 제주특별자치도

In [37]:
emart.위도 = emart_lat
emart.경도 = emart_lng

In [42]:
ts_strftime = [emart["개점 연도"][i].strftime('%Y-%m-%d') for i in range(len(emart["개점 연도"]))]

In [43]:
ts_strftime

['2008-07-28',
 '2004-10-07',
 '1993-11-12',
 '2008-10-16',
 '2012-05-29',
 '2004-09-22',
 '2009-03-19',
 '2011-01-21',
 '2000-06-01',
 '2001-04-19',
 '2008-09-04',
 '2007-02-08',
 '2001-08-06',
 '2000-01-01',
 '2010-06-10',
 '2005-02-24',
 '1999-07-29',
 '2001-05-24',
 '2001-01-20',
 '2000-03-09',
 '2009-04-21',
 '1999-08-26',
 '2008-05-15',
 '2009-09-26',
 '1999-08-29',
 '2007-11-08',
 '2009-10-22',
 '2001-11-28',
 '2012-01-10',
 '2006-07-27',
 '2008-12-23',
 '2003-08-21',
 '2005-12-20',
 '2005-09-09',
 '2009-08-07',
 '1994-09-08',
 '2015-06-18',
 '2014-07-24',
 '1998-07-01',
 '2005-11-30',
 '2008-05-22',
 '2013-08-08',
 '2010-12-23',
 '2015-09-03',
 '2005-08-25',
 '2001-09-20',
 '2007-01-24',
 '2010-12-09',
 '1999-02-08',
 '1998-07-01',
 '1996-11-30',
 '2010-09-08',
 '1997-08-14',
 '1998-07-01',
 '2004-08-13',
 '2011-08-31',
 '2007-12-21',
 '2012-08-17',
 '2009-09-17',
 '2003-05-23',
 '2015-12-03',
 '2015-01-29',
 '1999-11-25',
 '2000-05-04',
 '2008-10-09',
 '2004-07-20',
 '2005-12-19',
 '2018-12-13',
 '2013-07-15',
 '2000-06-27',
 '2000-06-27',
 '2001-10-23',
 '2010-08-12',
 '2008-05-30',
 '2006-09-22',
 '1999-05-09',
 '2001-02-07',
 '2002-12-12',
 '2005-04-26',
 '2002-12-24',
 '2004-01-27',
 '2003-11-20',
 '1999-03-20',
 '2005-11-22',
 '2006-10-31',
 '2002-04-24',
 '2011-12-22',
 '2015-02-05',
 '2009-12-21',
 '1998-06-27',
 '2001-10-15',
 '2001-04-30',
 '2012-12-13',
 '2010-12-21',
 '2012-04-05',
 '2008-10-01',
 '2012-02-02',
 '2006-10-20',
 '2003-08-06',
 '2003-07-24',
 '2003-12-05',
 '2002-03-12',
 '2000-04-06',
 '2002-10-24',
 '1999-11-17',
 '2001-04-25',
 '2001-02-27',
 '2004-09-03',
 '2002-04-10',
 '2002-04-10',
 '2006-06-15',
 '2002-06-15',
 '2011-12-15',
 '1998-01-01',
 '2007-04-12',
 '2004-11-12',
 '2004-02-26',
 '2001-12-12',
 '2004-09-16',
 '2016-06-23',
 '2002-12-12',
 '2010-12-30',
 '2004-08-03',
 '2000-08-31',
 '2002-06-24',
 '2005-07-01',
 '2004-06-08',
 '2006-07-04',
 '1998-06-18',
 '2007-07-19',
 '2001-04-10',
 '1997-04-29',
 '2006-10-12',
 '1998-12-03',
 '2021-03-01',
 '2000-12-19',
 '2005-07-27',
 '2001-12-23',
 '2006-06-08',
 '2003-08-29',
 '1996-11-22']

In [44]:
emart["개점 연도"] = ts_strftime

In [45]:
emart

,지역,지점명,주소,위도,경도,3km내 이마트,3km내 경쟁 대형마트,부지 공시지가,주차 시설,대중 교통,개점 연도,특징
0,서울특별시,청계천점,중구 청계천로 400 (황학동),37.571015,127.022913,NaN,NaN,NaN,1000.0,NaN,2008-07-28,NaN
1,NaN,용산점,용산구 한강대로23길 55 (한강로3가),37.529444,126.965556,NaN,NaN,NaN,2100.0,"용산역[연결], 신용산역",2004-10-07,NaN
2,NaN,창동점,도봉구 노해로65길 4 (창동),37.651667,127.046944,NaN,NaN,NaN,159.0,창동역,1993-11-12,이마트 1호점.
3,NaN,미아점,성북구 도봉로 17 (길음동),37.610891,127.029824,NaN,NaN,NaN,195.0,미아사거리역,2008-10-16,NaN
4,NaN,하월곡점,성북구 종암로 167 (하월곡동),37.604873,127.031185,NaN,NaN,NaN,760.0,NaN,2012-05-29,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
136,NaN,순천점,순천시 팔마로 191 (덕암동),34.942448,127.508434,NaN,NaN,NaN,700.0,순천역,2005-07-27,NaN
137,NaN,여수점,여수시 좌수영로 277 (오림동),34.758000,127.714973,NaN,NaN,NaN,510.0,여수종합버스터미널,2001-12-23,NaN
138,제주특별자치도,서귀포점,서귀포시 일주동로 9209 (법환동),33.248333,126.509167,NaN,NaN,NaN,480.0,서귀포시외버스터미널,2006-06-08,NaN
139,NaN,신제주점,제주시 1100로 3348 (노형동),33.484904,126.480517,NaN,NaN,NaN,297.0,NaN,2003-08-29,NaN
140,NaN,제주점,제주시 탑동로 38 (삼도이동),33.517929,126.521324,NaN,NaN,NaN,540.0,NaN,1996-11-22,NaN

In [46]:
emart.to_excel("이마트 데이터.xlsx", encoding="UTF-8",index=False)

In [11]:
# 트레이더스 데이터 위도 경도
emarttr = pd.read_excel("../TeamProjectData/이마트 트레이더스 데이터.xlsx")
emarttr.지역.fillna(method='pad',inplace=True)
emarttr

,지역,지점명,주소,위도,경도,3km내 이마트,3km내 경쟁 대형마트,부지 공시지가,주차 시설,대중 교통
0,수도권,구성점,경기도 용인시 기흥구 용구대로 2457,NaN,NaN,NaN,NaN,NaN,851,구성역
1,수도권,송림점,인천광역시 동구 봉수대로 82,NaN,NaN,NaN,NaN,NaN,934,NaN
2,수도권,안산점,경기도 안산시 단원구 중앙대로 397,NaN,NaN,NaN,NaN,NaN,522,안산역
3,수도권,수원점,경기도 수원시 영통구 삼성로 2,NaN,NaN,NaN,NaN,NaN,705,망포역
4,수도권,킨텍스점,경기도 고양시 일산서구 킨텍스로 171,NaN,NaN,NaN,NaN,NaN,1374,NaN
5,수도권,SF하남점,경기도 하남시 미사대로 750,NaN,NaN,NaN,NaN,NaN,6200,하남검단산역
6,수도권,고양점,경기도 고양시 덕양구 고양대로 1955,NaN,NaN,NaN,NaN,NaN,4500,삼송역
7,수도권,군포점,경기도 군포시 삼성로 74,NaN,NaN,NaN,NaN,NaN,714,NaN
8,수도권,김포점,경기도 김포시 김포대로 715,NaN,NaN,NaN,NaN,NaN,688,풍무역
9,수도권,부천점,경기도 부천시 옥길동 768,NaN,NaN,NaN,NaN,NaN,1866,NaN
10,수도권,위례점,경기도 하남시 위례대로 200,NaN,NaN,NaN,NaN,NaN,1843,NaN
11,수도권,월계점,서울특별시 노원구 마들로3길 17,NaN,NaN,NaN,NaN,NaN,1274,광운대역
12,기타 지역,월평점,대전광역시 서구 한밭대로 580,NaN,NaN,NaN,NaN,NaN,953,월평역
13,기타 지역,서면점,부산광역시 부산진구 시민공원로 31,NaN,NaN,NaN,NaN,NaN,840,"국철 부전역, 부산진구청"
14,기타 지역,비산점,대구광역시 서구 팔달로 54,NaN,NaN,NaN,NaN,NaN,607,"공단역, 서대구고속버스터미널"
15,기타 지역,천안아산점,충남 아산시 배방읍 고속철대로 133,NaN,NaN,NaN,NaN,NaN,785,"천안아산역, 아산역"
16,기타 지역,양산점,경상남도 양산시 평산로 16,NaN,NaN,NaN,NaN,NaN,547,NaN
17,기타 지역,명지점,부산광역시 강서구 명지국제6로 168 (명지동),NaN,NaN,NaN,NaN,NaN,1273,NaN

In [14]:
emarttr_branch = emarttr.지점명

In [15]:
emarttr_branch_name = ["이마트트레이더스 "+ name  for name in emarttr_branch]
emarttr_branch_name

['이마트트레이더스 구성점',
 '이마트트레이더스 송림점',
 '이마트트레이더스 안산점',
 '이마트트레이더스 수원점',
 '이마트트레이더스 킨텍스점',
 '이마트트레이더스 SF하남점',
 '이마트트레이더스 고양점',
 '이마트트레이더스 군포점',
 '이마트트레이더스 김포점',
 '이마트트레이더스 부천점',
 '이마트트레이더스 위례점',
 '이마트트레이더스 월계점',
 '이마트트레이더스 월평점',
 '이마트트레이더스 서면점',
 '이마트트레이더스 비산점',
 '이마트트레이더스 천안아산점',
 '이마트트레이더스 양산점',
 '이마트트레이더스 명지점']

In [16]:
emarttr_address = []
emarttr_lat = []
emarttr_lng = []

for name in emarttr_branch_name:
    tmp = gmaps.geocode(name, language = "ko")
    emarttr_address.append(tmp[0].get("formatted_address"))
    
    tmp_loc = tmp[0].get("geometry")
    
    emarttr_lat.append(tmp_loc["location"]["lat"])
    
    emarttr_lng.append(tmp_loc["location"]["lng"])
    
    print(name + "--->" + tmp[0].get("formatted_address"))

이마트트레이더스 구성점--->대한민국 경기도 용인시 기흥구 보정동 용구대로 2457
이마트트레이더스 송림점--->대한민국 인천광역시 동구 송림동 296-2
이마트트레이더스 안산점--->대한민국 경기도 안산시 단원구 원곡본동 중앙대로 397
이마트트레이더스 수원점--->대한민국 경기도 수원시 영통구 망포동 삼성로 2
이마트트레이더스 킨텍스점--->대한민국 경기도 고양시 일산서구 송포동 킨텍스로 171
이마트트레이더스 SF하남점--->대한민국 경기도 하남시 신장동 미사대로 750
이마트트레이더스 고양점--->대한민국 경기도 고양시 덕양구 동산동 고양대로 1955 스타 필드 고양 B2 층
이마트트레이더스 군포점--->대한민국 경기도 군포시 당동 삼성로 74
이마트트레이더스 김포점--->대한민국 경기도 김포시 풍무동 16-10
이마트트레이더스 부천점--->대한민국 경기도 부천시 계수동 옥길로 1
이마트트레이더스 위례점--->대한민국 경기도 하남시 학암동 위례대로 200 KR
이마트트레이더스 월계점--->대한민국 서울특별시 노원구 월계동 333-1
이마트트레이더스 월평점--->대한민국 대전광역시 서구 월평동 510
이마트트레이더스 서면점--->대한민국 부산광역시 부산진구 부암1동 시민공원로 31
이마트트레이더스 비산점--->대한민국 대구광역시 서구 비산동 팔달로 54
이마트트레이더스 천안아산점--->대한민국 충청남도 아산시 배방읍 고속철대로 133
이마트트레이더스 양산점--->대한민국 경상남도 양산시 평산동 평산로 16
이마트트레이더스 명지점--->대한민국 부산광역시 강서구 명지동 국제6로 168 지하 B2F

In [17]:
emarttr.위도 = emarttr_lat
emarttr.경도 = emarttr_lng

In [19]:
emarttr

,지역,지점명,주소,위도,경도,3km내 이마트,3km내 경쟁 대형마트,부지 공시지가,주차 시설,대중 교통
0,수도권,구성점,경기도 용인시 기흥구 용구대로 2457,37.304958,127.105103,NaN,NaN,NaN,851,구성역
1,수도권,송림점,인천광역시 동구 봉수대로 82,37.483056,126.660556,NaN,NaN,NaN,934,NaN
2,수도권,안산점,경기도 안산시 단원구 중앙대로 397,37.331175,126.784762,NaN,NaN,NaN,522,안산역
3,수도권,수원점,경기도 수원시 영통구 삼성로 2,37.245700,127.048032,NaN,NaN,NaN,705,망포역
4,수도권,킨텍스점,경기도 고양시 일산서구 킨텍스로 171,37.661667,126.744167,NaN,NaN,NaN,1374,NaN
5,수도권,SF하남점,경기도 하남시 미사대로 750,37.547474,127.224523,NaN,NaN,NaN,6200,하남검단산역
6,수도권,고양점,경기도 고양시 덕양구 고양대로 1955,37.646521,126.892983,NaN,NaN,NaN,4500,삼송역
7,수도권,군포점,경기도 군포시 삼성로 74,37.339771,126.934090,NaN,NaN,NaN,714,NaN
8,수도권,김포점,경기도 김포시 김포대로 715,37.612586,126.730652,NaN,NaN,NaN,688,풍무역
9,수도권,부천점,경기도 부천시 옥길동 768,37.461433,126.813638,NaN,NaN,NaN,1866,NaN
10,수도권,위례점,경기도 하남시 위례대로 200,37.480180,127.148541,NaN,NaN,NaN,1843,NaN
11,수도권,월계점,서울특별시 노원구 마들로3길 17,37.627831,127.061399,NaN,NaN,NaN,1274,광운대역
12,기타 지역,월평점,대전광역시 서구 한밭대로 580,36.357640,127.362995,NaN,NaN,NaN,953,월평역
13,기타 지역,서면점,부산광역시 부산진구 시민공원로 31,35.163910,129.052599,NaN,NaN,NaN,840,"국철 부전역, 부산진구청"
14,기타 지역,비산점,대구광역시 서구 팔달로 54,35.889877,128.555970,NaN,NaN,NaN,607,"공단역, 서대구고속버스터미널"
15,기타 지역,천안아산점,충남 아산시 배방읍 고속철대로 133,36.796556,127.105777,NaN,NaN,NaN,785,"천안아산역, 아산역"
16,기타 지역,양산점,경상남도 양산시 평산로 16,35.382194,129.152849,NaN,NaN,NaN,547,NaN
17,기타 지역,명지점,부산광역시 강서구 명지국제6로 168 (명지동),35.092999,128.918500,NaN,NaN,NaN,1273,NaN

In [21]:
emarttr.to_excel("이마트 트레이더스 데이터.xlsx", encoding="UTF-8",index=False)