In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib
from matplotlib import font_manager, rc
sns.set(style='darkgrid')


rc('font', family='AppleGothic')
matplotlib.rcParams['axes.unicode_minus'] = False
%matplotlib inline

import warnings
warnings.filterwarnings("ignore")

In [2]:
emart = pd.read_excel("../../데이터/emart(최종.ver1).xlsx",usecols="A,C,F,T,V:W,Z:AB")
emart

,지점명,3km이마트,3km경쟁마트,1인당지방세부담액(천원),1인가구구성원수,다인가구구성원수,카페(1년),등록자동차대수,점포형태
0,청계천점,1,1,10088.84,20803,105317,323,51736,0
1,용산점,1,1,3261.61,34240,195153,85,76521,0
2,창동점,0,3,539.75,30848,299301,217,96435,0
3,미아점,1,2,779.74,55136,387012,162,119321,0
4,하월곡점,2,2,779.74,55136,387012,166,119321,0
...,...,...,...,...,...,...,...,...,...
160,시지점,1,2,1098.98,35853,391583,1,218885,2
161,부평점,1,7,149.36,48607,455339,10,228866,2
162,덕이점,2,2,1198.70,84595,991584,12,418739,2
163,서부산점,1,0,769.06,27709,188374,32,89888,2
164,상무점,1,1,942.95,38197,261653,55,148351,2

In [3]:
emart = emart[emart.점포형태 != 1]
emart.reset_index(drop=True, inplace = True)

In [4]:
emart.corr()

,3km이마트,3km경쟁마트,1인당지방세부담액(천원),1인가구구성원수,다인가구구성원수,카페(1년),등록자동차대수,점포형태
3km이마트,1.000000,0.359420,0.023707,0.158586,0.111595,0.060460,-0.010558,0.277844
3km경쟁마트,0.359420,1.000000,-0.176114,0.204926,0.211360,-0.025519,0.156212,0.207728
1인당지방세부담액(천원),0.023707,-0.176114,1.000000,-0.035441,-0.024602,0.098559,-0.011195,-0.117813
1인가구구성원수,0.158586,0.204926,-0.035441,1.000000,0.907413,0.030549,0.858783,0.044529
다인가구구성원수,0.111595,0.211360,-0.024602,0.907413,1.000000,0.090763,0.925256,0.022409
카페(1년),0.060460,-0.025519,0.098559,0.030549,0.090763,1.000000,0.055054,-0.245810
등록자동차대수,-0.010558,0.156212,-0.011195,0.858783,0.925256,0.055054,1.000000,0.000578
점포형태,0.277844,0.207728,-0.117813,0.044529,0.022409,-0.245810,0.000578,1.000000

In [5]:
df_close = emart[emart.점포형태 == 2]

In [6]:
columns_li=['1인당지방세부담액(천원)', '다인가구구성원수', '카페(1년)', '등록자동차대수']

for col in columns_li:
    _min=round(df_close[col].mean()*0.8,3)
    _max=round(df_close[col].mean()*1.2,3)
    print(col)
    print('평균값:',df_close[col].mean())
    print('최고값:',_max, '최저값:',_min)
    def df_value(row):
        if row<=_min:
            return 3
        elif (row>_min and row<=_max):
            return 2
        elif row>_max:
            return 1
    emart[col]=emart[col].apply(df_value)

1인당지방세부담액(천원)
평균값: 851.65
최고값: 1021.98 최저값: 681.32
다인가구구성원수
평균값: 430203.22222222225
최고값: 516243.867 최저값: 344162.578
카페(1년)
평균값: 13.11111111111111
최고값: 15.733 최저값: 10.489
등록자동차대수
평균값: 200925.55555555556
최고값: 241110.667 최저값: 160740.444

In [7]:
#하 중 상
columns_li=['3km이마트','3km경쟁마트', '1인가구구성원수']
for col in columns_li:
    _min=round(df_close[col].mean()*0.8,3)
    _max=round(df_close[col].mean()*1.2,3)
    print(col)
    print('평균값:',df_close[col].mean())
    print('최고값:',_max, '최저값:',_min)
    def df_value2(row):
        if row<=_min:
            return 1
        elif (row>_min and row<=_max):
            return 2
        elif row>_max:
            return 3
    emart[col]=emart[col].apply(df_value2)

3km이마트
평균값: 1.0
최고값: 1.2 최저값: 0.8
3km경쟁마트
평균값: 2.111111111111111
최고값: 2.533 최저값: 1.689
1인가구구성원수
평균값: 51076.0
최고값: 61291.2 최저값: 40860.8

In [8]:
emart

,지점명,3km이마트,3km경쟁마트,1인당지방세부담액(천원),1인가구구성원수,다인가구구성원수,카페(1년),등록자동차대수,점포형태
0,청계천점,2,1,1,1,3,1,3,0
1,용산점,2,1,1,1,3,1,3,0
2,창동점,1,3,3,1,3,1,3,0
3,미아점,2,2,2,2,2,1,3,0
4,하월곡점,3,2,2,2,2,1,3,0
...,...,...,...,...,...,...,...,...,...
142,시지점,2,2,1,1,2,3,2,2
143,부평점,2,3,3,2,2,3,2,2
144,덕이점,3,2,1,3,1,2,1,2
145,서부산점,2,1,2,1,3,1,3,2
146,상무점,2,1,2,1,3,1,3,2

In [ ]:
emart['점수']=emart.iloc[:,1:8].sum(axis=1)

In [ ]:
emart

In [ ]:
for i in emart.keys()[1:]:
    print(emart[i].value_counts())

In [14]:
from sklearn.linear_model import LogisticRegression
LR=LogisticRegression()

In [17]:
x=emart.iloc[:,1:-1]
y=emart['점포형태']

In [18]:
X = np.array(x).reshape(-1,1)

In [19]:
LR.fit(x, y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [20]:
LR.score(x,y)

0.9795918367346939

In [22]:
pred=LR.predict_proba(x)

In [23]:
for i in range(len(emart)):
#     if pred[i][1]>=0.5:
    print(emart['지점명'][i],'------>',pred[i][1])

청계천점 ------> 0.03099278015886855
용산점 ------> 0.03099278015886855
창동점 ------> 0.01080976818577512
미아점 ------> 0.03585196233730025
하월곡점 ------> 0.13040353360912427
월계점 ------> 0.03915282913053831
묵동점 ------> 0.1411353891835603
상봉점 ------> 0.1496779263804101
성수점 ------> 0.11424786997011326
왕십리점 ------> 0.11424786997011326
자양점 ------> 0.03946687708812696
명일점 ------> 0.007794099048369758
천호점 ------> 0.008344265809226191
가든파이브점 ------> 0.03973000114433317
양재점 ------> 0.010252137678999027
역삼점 ------> 0.011997620463702547
수서점 ------> 0.053201427135980923
이수점 ------> 0.010085920373791184
가양점 ------> 0.011997620463702547
목동점 ------> 0.03286049854995933
신월점 ------> 0.007289189126549867
여의도점 ------> 0.036140529645975465
영등포점 ------> 0.14785118151263746
구로점 ------> 0.03507410794270285
신도림점 ------> 0.1278462799100534
수색점 ------> 0.008534563563359932
은평점 ------> 0.008534563563359932
마포점 ------> 0.036140529645975465
동백점 ------> 0.013347890171493276
보라점 ------> 0.01428444182755554
수지점 ------> 0.051734573815567675
용인점 ------> 0.013347890171493276
죽전점 ------> 0.051734573815567675
흥덕점 ------> 0.015285688359704513
일산점 ------> 0.05521379404549936
킨텍스점 ------> 0.015285688359704513
풍산점 ------> 0.05521379404549936
화정점 ------> 0.01428444182755554
남양주점 ------> 0.007868651508475693
다산점 ------> 0.007868651508475693
별내점 ------> 0.007868651508475693
진접점 ------> 0.007868651508475693
광교점 ------> 0.013347890171493276
서수원점 ------> 0.01428444182755554
수원점 ------> 0.015285688359704513
광명소하점 ------> 0.008424036069154393
부천점 ------> 0.05641218319882416
중동점 ------> 0.060186013020557934
분당점 ------> 0.013347890171493276
성남점 ------> 0.013347890171493276
안양점 ------> 0.04009768325796294
평촌점 ------> 0.04573889207401877
파주점 ------> 0.008758346634617322
파주운정점 ------> 0.008758346634617322
동탄점 ------> 0.013347890171493276
화성봉담점 ------> 0.013347890171493276
경기광주점 ------> 0.008758346634617322
고잔점 ------> 0.013347890171493276
과천점 ------> 0.007868651508475693
김포한강점 ------> 0.008758346634617322
산본점 ------> 0.008616137242217596
시화점 ------> 0.010973892487537907
안성점 ------> 0.007868651508475693
양주점 ------> 0.007868651508475693
여주점 ------> 0.007868651508475693
오산점 ------> 0.007868651508475693
의왕점 ------> 0.007868651508475693
의정부점 ------> 0.009136516643435984
이천점 ------> 0.007868651508475693
평택점 ------> 0.013474844547298458
포천점 ------> 0.007868651508475693
하남점 ------> 0.007868651508475693
검단점 ------> 0.01613724406426953
계양점 ------> 0.018647182450552427
동인천점 ------> 0.007868651508475693
연수점 ------> 0.010498764016583048
인천공항점 ------> 0.007868651508475693
강릉점 ------> 0.007868651508475693
동해점 ------> 0.008616137242217596
속초점 ------> 0.007868651508475693
원주점 ------> 0.012111889815506673
춘천점 ------> 0.009223790286619724
태백점 ------> 0.28444478646904164
대전터미널점 ------> 0.00943395548921418
둔산점 ------> 0.015039102427373026
세종점 ------> 0.010349956621625103
제천점 ------> 0.30343034085566867
청주점 ------> 0.015985612128964422
충주점 ------> 0.00943395548921418
천안점 ------> 0.051734573815567675
천안서북점 ------> 0.013347890171493276
천안터미널점 ------> 0.01428444182755554
펜타포트점 ------> 0.051734573815567675
보령점 ------> 0.007868651508475693
서산점 ------> 0.007868651508475693
아산점 ------> 0.010349956621625103
금정점 ------> 0.008616137242217596
문현점 ------> 0.010098697641206557
사상점 ------> 0.008616137242217596
연제점 ------> 0.009223790286619724
해운대점 ------> 0.008758346634617322
감삼점 ------> 0.060731033014518154
성서점 ------> 0.05692509888439123
월배점 ------> 0.014746976881002904
반야월점 ------> 0.011330463024094036
칠성점 ------> 0.011223482267816706
만촌점 ------> 0.008758346634617322
울산점 ------> 0.01080976818577512
경산점 ------> 0.008424036069154393
구미점 ------> 0.010973892487537907
동구미점 ------> 0.010252137678999027
김천점 ------> 0.28444478646904164
상주점 ------> 0.28444478646904164
안동점 ------> 0.055514700105344345
영천점 ------> 0.007868651508475693
포항점 ------> 0.013474844547298458
포항이동점 ------> 0.014420173739373605
김해점 ------> 0.015430785261586756
마산점 ------> 0.013347890171493276
사천점 ------> 0.007868651508475693
양산점 ------> 0.010349956621625103
진주점 ------> 0.012111889815506673
창원점 ------> 0.01428444182755554
통영점 ------> 0.008616137242217596
광산점 ------> 0.011223482267816706
광주점 ------> 0.009223790286619724
동광주점 ------> 0.008424036069154393
봉선점 ------> 0.008616137242217596
군산점 ------> 0.007868651508475693
남원점 ------> 0.008616137242217596
익산점 ------> 0.28444478646904164
전주점 ------> 0.01672588024962687
목포점 ------> 0.009223790286619724
순천점 ------> 0.008616137242217596
여수점 ------> 0.007868651508475693
서귀포점 ------> 0.007868651508475693
신제주점 ------> 0.013474844547298458
제주점 ------> 0.013474844547298458
안산점(공단점) ------> 0.7139072896694071
공항점 ------> 0.3570866625296447
장안점 ------> 0.6681170282019954
학성점 ------> 0.6684005568106847
시지점 ------> 0.6358061532101966
부평점 ------> 0.7247136338520923
덕이점 ------> 0.6144787042348474
서부산점 ------> 0.033861977773950815
상무점 ------> 0.033861977773950815

In [24]:
for i in range(len(emart)):
    if pred[i][1] > pred[i][0]:
        print(emart["지점명"][i],"----> 생존확률:{} / 폐점확률:{} ---->{}".format(pred[i][0],pred[i][1],"폐점확정"))
    else:
        print(emart["지점명"][i],"----> 생존확률:{} / 폐점확률:{} ---->{}".format(pred[i][0],pred[i][1],"생존확정"))

청계천점 ----> 생존확률:0.9690072198411315 / 폐점확률:0.03099278015886855 ---->생존확정
용산점 ----> 생존확률:0.9690072198411315 / 폐점확률:0.03099278015886855 ---->생존확정
창동점 ----> 생존확률:0.9891902318142248 / 폐점확률:0.01080976818577512 ---->생존확정
미아점 ----> 생존확률:0.9641480376626997 / 폐점확률:0.03585196233730025 ---->생존확정
하월곡점 ----> 생존확률:0.8695964663908757 / 폐점확률:0.13040353360912427 ---->생존확정
월계점 ----> 생존확률:0.9608471708694617 / 폐점확률:0.03915282913053831 ---->생존확정
묵동점 ----> 생존확률:0.8588646108164397 / 폐점확률:0.1411353891835603 ---->생존확정
상봉점 ----> 생존확률:0.8503220736195899 / 폐점확률:0.1496779263804101 ---->생존확정
성수점 ----> 생존확률:0.8857521300298867 / 폐점확률:0.11424786997011326 ---->생존확정
왕십리점 ----> 생존확률:0.8857521300298867 / 폐점확률:0.11424786997011326 ---->생존확정
자양점 ----> 생존확률:0.960533122911873 / 폐점확률:0.03946687708812696 ---->생존확정
명일점 ----> 생존확률:0.9922059009516302 / 폐점확률:0.007794099048369758 ---->생존확정
천호점 ----> 생존확률:0.9916557341907738 / 폐점확률:0.008344265809226191 ---->생존확정
가든파이브점 ----> 생존확률:0.9602699988556669 / 폐점확률:0.03973000114433317 ---->생존확정
양재점 ----> 생존확률:0.989747862321001 / 폐점확률:0.010252137678999027 ---->생존확정
역삼점 ----> 생존확률:0.9880023795362974 / 폐점확률:0.011997620463702547 ---->생존확정
수서점 ----> 생존확률:0.946798572864019 / 폐점확률:0.053201427135980923 ---->생존확정
이수점 ----> 생존확률:0.9899140796262088 / 폐점확률:0.010085920373791184 ---->생존확정
가양점 ----> 생존확률:0.9880023795362974 / 폐점확률:0.011997620463702547 ---->생존확정
목동점 ----> 생존확률:0.9671395014500407 / 폐점확률:0.03286049854995933 ---->생존확정
신월점 ----> 생존확률:0.9927108108734501 / 폐점확률:0.007289189126549867 ---->생존확정
여의도점 ----> 생존확률:0.9638594703540245 / 폐점확률:0.036140529645975465 ---->생존확정
영등포점 ----> 생존확률:0.8521488184873626 / 폐점확률:0.14785118151263746 ---->생존확정
구로점 ----> 생존확률:0.9649258920572972 / 폐점확률:0.03507410794270285 ---->생존확정
신도림점 ----> 생존확률:0.8721537200899466 / 폐점확률:0.1278462799100534 ---->생존확정
수색점 ----> 생존확률:0.9914654364366401 / 폐점확률:0.008534563563359932 ---->생존확정
은평점 ----> 생존확률:0.9914654364366401 / 폐점확률:0.008534563563359932 ---->생존확정
마포점 ----> 생존확률:0.9638594703540245 / 폐점확률:0.036140529645975465 ---->생존확정
동백점 ----> 생존확률:0.9866521098285067 / 폐점확률:0.013347890171493276 ---->생존확정
보라점 ----> 생존확률:0.9857155581724445 / 폐점확률:0.01428444182755554 ---->생존확정
수지점 ----> 생존확률:0.9482654261844323 / 폐점확률:0.051734573815567675 ---->생존확정
용인점 ----> 생존확률:0.9866521098285067 / 폐점확률:0.013347890171493276 ---->생존확정
죽전점 ----> 생존확률:0.9482654261844323 / 폐점확률:0.051734573815567675 ---->생존확정
흥덕점 ----> 생존확률:0.9847143116402954 / 폐점확률:0.015285688359704513 ---->생존확정
일산점 ----> 생존확률:0.9447862059545007 / 폐점확률:0.05521379404549936 ---->생존확정
킨텍스점 ----> 생존확률:0.9847143116402954 / 폐점확률:0.015285688359704513 ---->생존확정
풍산점 ----> 생존확률:0.9447862059545007 / 폐점확률:0.05521379404549936 ---->생존확정
화정점 ----> 생존확률:0.9857155581724445 / 폐점확률:0.01428444182755554 ---->생존확정
남양주점 ----> 생존확률:0.9921313484915243 / 폐점확률:0.007868651508475693 ---->생존확정
다산점 ----> 생존확률:0.9921313484915243 / 폐점확률:0.007868651508475693 ---->생존확정
별내점 ----> 생존확률:0.9921313484915243 / 폐점확률:0.007868651508475693 ---->생존확정
진접점 ----> 생존확률:0.9921313484915243 / 폐점확률:0.007868651508475693 ---->생존확정
광교점 ----> 생존확률:0.9866521098285067 / 폐점확률:0.013347890171493276 ---->생존확정
서수원점 ----> 생존확률:0.9857155581724445 / 폐점확률:0.01428444182755554 ---->생존확정
수원점 ----> 생존확률:0.9847143116402954 / 폐점확률:0.015285688359704513 ---->생존확정
광명소하점 ----> 생존확률:0.9915759639308456 / 폐점확률:0.008424036069154393 ---->생존확정
부천점 ----> 생존확률:0.9435878168011759 / 폐점확률:0.05641218319882416 ---->생존확정
중동점 ----> 생존확률:0.9398139869794421 / 폐점확률:0.060186013020557934 ---->생존확정
분당점 ----> 생존확률:0.9866521098285067 / 폐점확률:0.013347890171493276 ---->생존확정
성남점 ----> 생존확률:0.9866521098285067 / 폐점확률:0.013347890171493276 ---->생존확정
안양점 ----> 생존확률:0.9599023167420371 / 폐점확률:0.04009768325796294 ---->생존확정
평촌점 ----> 생존확률:0.9542611079259813 / 폐점확률:0.04573889207401877 ---->생존확정
파주점 ----> 생존확률:0.9912416533653827 / 폐점확률:0.008758346634617322 ---->생존확정
파주운정점 ----> 생존확률:0.9912416533653827 / 폐점확률:0.008758346634617322 ---->생존확정
동탄점 ----> 생존확률:0.9866521098285067 / 폐점확률:0.013347890171493276 ---->생존확정
화성봉담점 ----> 생존확률:0.9866521098285067 / 폐점확률:0.013347890171493276 ---->생존확정
경기광주점 ----> 생존확률:0.9912416533653827 / 폐점확률:0.008758346634617322 ---->생존확정
고잔점 ----> 생존확률:0.9866521098285067 / 폐점확률:0.013347890171493276 ---->생존확정
과천점 ----> 생존확률:0.9921313484915243 / 폐점확률:0.007868651508475693 ---->생존확정
김포한강점 ----> 생존확률:0.9912416533653827 / 폐점확률:0.008758346634617322 ---->생존확정
산본점 ----> 생존확률:0.9913838627577825 / 폐점확률:0.008616137242217596 ---->생존확정
시화점 ----> 생존확률:0.9890261075124621 / 폐점확률:0.010973892487537907 ---->생존확정
안성점 ----> 생존확률:0.9921313484915243 / 폐점확률:0.007868651508475693 ---->생존확정
양주점 ----> 생존확률:0.9921313484915243 / 폐점확률:0.007868651508475693 ---->생존확정
여주점 ----> 생존확률:0.9921313484915243 / 폐점확률:0.007868651508475693 ---->생존확정
오산점 ----> 생존확률:0.9921313484915243 / 폐점확률:0.007868651508475693 ---->생존확정
의왕점 ----> 생존확률:0.9921313484915243 / 폐점확률:0.007868651508475693 ---->생존확정
의정부점 ----> 생존확률:0.990863483356564 / 폐점확률:0.009136516643435984 ---->생존확정
이천점 ----> 생존확률:0.9921313484915243 / 폐점확률:0.007868651508475693 ---->생존확정
평택점 ----> 생존확률:0.9865251554527016 / 폐점확률:0.013474844547298458 ---->생존확정
포천점 ----> 생존확률:0.9921313484915243 / 폐점확률:0.007868651508475693 ---->생존확정
하남점 ----> 생존확률:0.9921313484915243 / 폐점확률:0.007868651508475693 ---->생존확정
검단점 ----> 생존확률:0.9838627559357305 / 폐점확률:0.01613724406426953 ---->생존확정
계양점 ----> 생존확률:0.9813528175494476 / 폐점확률:0.018647182450552427 ---->생존확정
동인천점 ----> 생존확률:0.9921313484915243 / 폐점확률:0.007868651508475693 ---->생존확정
연수점 ----> 생존확률:0.989501235983417 / 폐점확률:0.010498764016583048 ---->생존확정
인천공항점 ----> 생존확률:0.9921313484915243 / 폐점확률:0.007868651508475693 ---->생존확정
강릉점 ----> 생존확률:0.9921313484915243 / 폐점확률:0.007868651508475693 ---->생존확정
동해점 ----> 생존확률:0.9913838627577825 / 폐점확률:0.008616137242217596 ---->생존확정
속초점 ----> 생존확률:0.9921313484915243 / 폐점확률:0.007868651508475693 ---->생존확정
원주점 ----> 생존확률:0.9878881101844933 / 폐점확률:0.012111889815506673 ---->생존확정
춘천점 ----> 생존확률:0.9907762097133803 / 폐점확률:0.009223790286619724 ---->생존확정
태백점 ----> 생존확률:0.7155552135309584 / 폐점확률:0.28444478646904164 ---->생존확정
대전터미널점 ----> 생존확률:0.9905660445107858 / 폐점확률:0.00943395548921418 ---->생존확정
둔산점 ----> 생존확률:0.984960897572627 / 폐점확률:0.015039102427373026 ---->생존확정
세종점 ----> 생존확률:0.9896500433783749 / 폐점확률:0.010349956621625103 ---->생존확정
제천점 ----> 생존확률:0.6965696591443313 / 폐점확률:0.30343034085566867 ---->생존확정
청주점 ----> 생존확률:0.9840143878710356 / 폐점확률:0.015985612128964422 ---->생존확정
충주점 ----> 생존확률:0.9905660445107858 / 폐점확률:0.00943395548921418 ---->생존확정
천안점 ----> 생존확률:0.9482654261844323 / 폐점확률:0.051734573815567675 ---->생존확정
천안서북점 ----> 생존확률:0.9866521098285067 / 폐점확률:0.013347890171493276 ---->생존확정
천안터미널점 ----> 생존확률:0.9857155581724445 / 폐점확률:0.01428444182755554 ---->생존확정
펜타포트점 ----> 생존확률:0.9482654261844323 / 폐점확률:0.051734573815567675 ---->생존확정
보령점 ----> 생존확률:0.9921313484915243 / 폐점확률:0.007868651508475693 ---->생존확정
서산점 ----> 생존확률:0.9921313484915243 / 폐점확률:0.007868651508475693 ---->생존확정
아산점 ----> 생존확률:0.9896500433783749 / 폐점확률:0.010349956621625103 ---->생존확정
금정점 ----> 생존확률:0.9913838627577825 / 폐점확률:0.008616137242217596 ---->생존확정
문현점 ----> 생존확률:0.9899013023587935 / 폐점확률:0.010098697641206557 ---->생존확정
사상점 ----> 생존확률:0.9913838627577825 / 폐점확률:0.008616137242217596 ---->생존확정
연제점 ----> 생존확률:0.9907762097133803 / 폐점확률:0.009223790286619724 ---->생존확정
해운대점 ----> 생존확률:0.9912416533653827 / 폐점확률:0.008758346634617322 ---->생존확정
감삼점 ----> 생존확률:0.9392689669854819 / 폐점확률:0.060731033014518154 ---->생존확정
성서점 ----> 생존확률:0.9430749011156088 / 폐점확률:0.05692509888439123 ---->생존확정
월배점 ----> 생존확률:0.9852530231189971 / 폐점확률:0.014746976881002904 ---->생존확정
반야월점 ----> 생존확률:0.988669536975906 / 폐점확률:0.011330463024094036 ---->생존확정
칠성점 ----> 생존확률:0.9887765177321833 / 폐점확률:0.011223482267816706 ---->생존확정
만촌점 ----> 생존확률:0.9912416533653827 / 폐점확률:0.008758346634617322 ---->생존확정
울산점 ----> 생존확률:0.9891902318142248 / 폐점확률:0.01080976818577512 ---->생존확정
경산점 ----> 생존확률:0.9915759639308456 / 폐점확률:0.008424036069154393 ---->생존확정
구미점 ----> 생존확률:0.9890261075124621 / 폐점확률:0.010973892487537907 ---->생존확정
동구미점 ----> 생존확률:0.989747862321001 / 폐점확률:0.010252137678999027 ---->생존확정
김천점 ----> 생존확률:0.7155552135309584 / 폐점확률:0.28444478646904164 ---->생존확정
상주점 ----> 생존확률:0.7155552135309584 / 폐점확률:0.28444478646904164 ---->생존확정
안동점 ----> 생존확률:0.9444852998946557 / 폐점확률:0.055514700105344345 ---->생존확정
영천점 ----> 생존확률:0.9921313484915243 / 폐점확률:0.007868651508475693 ---->생존확정
포항점 ----> 생존확률:0.9865251554527016 / 폐점확률:0.013474844547298458 ---->생존확정
포항이동점 ----> 생존확률:0.9855798262606263 / 폐점확률:0.014420173739373605 ---->생존확정
김해점 ----> 생존확률:0.9845692147384132 / 폐점확률:0.015430785261586756 ---->생존확정
마산점 ----> 생존확률:0.9866521098285067 / 폐점확률:0.013347890171493276 ---->생존확정
사천점 ----> 생존확률:0.9921313484915243 / 폐점확률:0.007868651508475693 ---->생존확정
양산점 ----> 생존확률:0.9896500433783749 / 폐점확률:0.010349956621625103 ---->생존확정
진주점 ----> 생존확률:0.9878881101844933 / 폐점확률:0.012111889815506673 ---->생존확정
창원점 ----> 생존확률:0.9857155581724445 / 폐점확률:0.01428444182755554 ---->생존확정
통영점 ----> 생존확률:0.9913838627577825 / 폐점확률:0.008616137242217596 ---->생존확정
광산점 ----> 생존확률:0.9887765177321833 / 폐점확률:0.011223482267816706 ---->생존확정
광주점 ----> 생존확률:0.9907762097133803 / 폐점확률:0.009223790286619724 ---->생존확정
동광주점 ----> 생존확률:0.9915759639308456 / 폐점확률:0.008424036069154393 ---->생존확정
봉선점 ----> 생존확률:0.9913838627577825 / 폐점확률:0.008616137242217596 ---->생존확정
군산점 ----> 생존확률:0.9921313484915243 / 폐점확률:0.007868651508475693 ---->생존확정
남원점 ----> 생존확률:0.9913838627577825 / 폐점확률:0.008616137242217596 ---->생존확정
익산점 ----> 생존확률:0.7155552135309584 / 폐점확률:0.28444478646904164 ---->생존확정
전주점 ----> 생존확률:0.9832741197503732 / 폐점확률:0.01672588024962687 ---->생존확정
목포점 ----> 생존확률:0.9907762097133803 / 폐점확률:0.009223790286619724 ---->생존확정
순천점 ----> 생존확률:0.9913838627577825 / 폐점확률:0.008616137242217596 ---->생존확정
여수점 ----> 생존확률:0.9921313484915243 / 폐점확률:0.007868651508475693 ---->생존확정
서귀포점 ----> 생존확률:0.9921313484915243 / 폐점확률:0.007868651508475693 ---->생존확정
신제주점 ----> 생존확률:0.9865251554527016 / 폐점확률:0.013474844547298458 ---->생존확정
제주점 ----> 생존확률:0.9865251554527016 / 폐점확률:0.013474844547298458 ---->생존확정
안산점(공단점) ----> 생존확률:0.2860927103305929 / 폐점확률:0.7139072896694071 ---->폐점확정
공항점 ----> 생존확률:0.6429133374703553 / 폐점확률:0.3570866625296447 ---->생존확정
장안점 ----> 생존확률:0.33188297179800463 / 폐점확률:0.6681170282019954 ---->폐점확정
학성점 ----> 생존확률:0.33159944318931533 / 폐점확률:0.6684005568106847 ---->폐점확정
시지점 ----> 생존확률:0.3641938467898034 / 폐점확률:0.6358061532101966 ---->폐점확정
부평점 ----> 생존확률:0.2752863661479077 / 폐점확률:0.7247136338520923 ---->폐점확정
덕이점 ----> 생존확률:0.3855212957651526 / 폐점확률:0.6144787042348474 ---->폐점확정
서부산점 ----> 생존확률:0.9661380222260492 / 폐점확률:0.033861977773950815 ---->생존확정
상무점 ----> 생존확률:0.9661380222260492 / 폐점확률:0.033861977773950815 ---->생존확정

In [25]:
for i in range(len(emart)):
    if pred[i][1] > 0.2:
        print(emart["지점명"][i],"----> 생존확률:{} / 폐점확률:{} ---->{}".format(pred[i][0],pred[i][1],"폐점가능성"))

태백점 ----> 생존확률:0.7155552135309584 / 폐점확률:0.28444478646904164 ---->폐점가능성
제천점 ----> 생존확률:0.6965696591443313 / 폐점확률:0.30343034085566867 ---->폐점가능성
김천점 ----> 생존확률:0.7155552135309584 / 폐점확률:0.28444478646904164 ---->폐점가능성
상주점 ----> 생존확률:0.7155552135309584 / 폐점확률:0.28444478646904164 ---->폐점가능성
익산점 ----> 생존확률:0.7155552135309584 / 폐점확률:0.28444478646904164 ---->폐점가능성
안산점(공단점) ----> 생존확률:0.2860927103305929 / 폐점확률:0.7139072896694071 ---->폐점가능성
공항점 ----> 생존확률:0.6429133374703553 / 폐점확률:0.3570866625296447 ---->폐점가능성
장안점 ----> 생존확률:0.33188297179800463 / 폐점확률:0.6681170282019954 ---->폐점가능성
학성점 ----> 생존확률:0.33159944318931533 / 폐점확률:0.6684005568106847 ---->폐점가능성
시지점 ----> 생존확률:0.3641938467898034 / 폐점확률:0.6358061532101966 ---->폐점가능성
부평점 ----> 생존확률:0.2752863661479077 / 폐점확률:0.7247136338520923 ---->폐점가능성
덕이점 ----> 생존확률:0.3855212957651526 / 폐점확률:0.6144787042348474 ---->폐점가능성